# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15NtiePRxy-gjVH35jp-4FYoluvBWLxo9
"""

import scipy.constants as sc
import astropy.constants as ac
import numpy as np
import matplotlib.pyplot as plt


c = sc.c

semi_major_axis = 149597887.5e3

eccentricity = 0.0167

theta = np.linspace(0,2*sc.pi, 100)

r = semi_major_axis*(1-eccentricity**2) / (1+eccentricity*np.sin(theta)) #distance of earth from solar system barycenter throughout a year

mu = sc.G * (ac.M_sun.value + ac.M_earth.value)

v = (mu*(2/r-1/semi_major_axis))**0.5

ab = v/c * np.sin(theta)

plt.plot(theta, np.degrees(ab)*3600)
plt.grid()
plt.xlabel('Angular distance [deg]'); plt.ylabel('Aberration [arcsec]');

plt.gca().spines[['right', 'top']].set_visible(False);